[package]
name = "assignment-1"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
jsonwebtoken = "9.3.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = {version = "1.0.140"}
todo_macros = {path = "./todo_macros"}
